apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gpt-researcher.configMapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gpt-researcher.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
